
version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: manufacturing_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: securepassword
    ports:
      - "5433:5432"
    volumes:
      - postgres_data_Agent1:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - manufacturing_network


  backend:
    build: 
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - "3001:3000"
    environment:
      - DATABASE_URL=postgresql://admin:securepassword@postgres:5432/manufacturing_db
      - NODE_ENV=development
      - PORT=3000
    depends_on:
      - postgres
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - manufacturing_network

  frontend:

    build: ./frontend
    ports:
      - "3002:80"
    depends_on:
      - backend
    networks:
      - manufacturing_network

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11435:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - manufacturing_network

volumes:
  postgres_data_Agent1:
  ollama_data:

networks:
  manufacturing_network:
    driver: bridge
